### ISSUE TITLE
400 Bad Request requesting http://localhost:3001

### ISSUE THREAD

**Issue by grandamp** [18F/identity-pki#21]
After `make run` I see:

>$ make run
>foreman start -p 3001
>10:30:39 web.1  | started with pid 23221
>10:30:42 web.1  | Puma starting in single mode...
>10:30:42 web.1  | * Version 3.11.4 (ruby 2.3.7-p456), codename: Love Song
>10:30:42 web.1  | * Min threads: 5, max threads: 5
>10:30:42 web.1  | * Environment: development
>10:30:42 web.1  | * Listening on tcp://localhost:3001
>10:30:42 web.1  | Use Ctrl-C to stop

Upon requesting `curl -v http://localhost:3001`, I get:

>$ curl -v http://localhost:3001
>* Rebuilt URL to: http://localhost:3001/
>*   Trying 127.0.0.1...
>* Connected to localhost (127.0.0.1) port 3001 (#0)
>> GET / HTTP/1.1
>> Host: localhost:3001
>> User-Agent: curl/7.47.0
>> Accept: */*
>> 
>< HTTP/1.1 400 Bad Request
>< X-Frame-Options: SAMEORIGIN
>< X-XSS-Protection: 1; mode=block
>< X-Content-Type-Options: nosniff
>< X-Download-Options: noopen
>< X-Permitted-Cross-Domain-Policies: none
>< Referrer-Policy: strict-origin-when-cross-origin
>< Content-Type: text/plain; charset=utf-8
>< Cache-Control: no-cache
>< X-Request-Id: a821b75b-84cd-4e26-82ce-67dfd995c7ee
>< X-Runtime: 0.002416
>< Transfer-Encoding: chunked
>< 
>* Connection #0 to host localhost left intact
>

**Comment by jgsmith-usds** [comment]
That is expected behavior. I'll update the README indicating that this application expects to be requested as a redirect from the IdP. Without a `Referer` header, it will return a 400 status.

**Comment by huynguyen22994** [comment]
good

**Comment by amoose** [comment]
Todd! Any luck testing with the Referer header?
