### ISSUE TITLE
Possible addition of the TWIC certificate chain

### ISSUE THREAD

**Issue by markrosenbaum** [18F/identity-pki#341]
I was wondering if the TWIC PKI  was eligible for addition to the list of allowed certificates for login.gov.

Some(possibly outdated) technical information about the certificate that may be relevant can be found on page 3 of this document: https://homeport.uscg.mil/Lists/Content/Attachments/61347/2017-TWIC001_Relocation%20of%20the%20TWIC%20CMS.pdf

**Comment by markrosenbaum** [comment]
Here is the confirmed current Authority Info Access extracted directly off the card.

> [1]Authority Info Access
     Access Method=Certification Authority Issuer (1.3.6.1.5.5.7.48.2)
     Alternative Name:
          URL=http://twicaia-twic.tsa.dhs.gov/AIA/CertsIssuedToTWICCA1.p7c
[2]Authority Info Access
     Access Method=Certification Authority Issuer (1.3.6.1.5.5.7.48.2)
     Alternative Name:
          URL=ldap://twicaia-twic.tsa.dhs.gov/cn=TWIC CA 1,ou=TSA Certification Authorities,o=U.S. Government,c=US?cACertificate;binary (ldap://twicaia-twic.tsa.dhs.gov/cn=TWIC%20CA%201,ou=TSA%20Certification%20Authorities,o=U.S.%20Government,c=US?cACertificate;binary)

**Comment by mitchellhenke** [comment]
Hello, thanks for opening an issue!

Our certificate set is based in part on the [Federal PKI Graph](https://playbooks.idmanagement.gov/fpki/tools/fpkigraph/), and issuing certificates must be valid and issued by `Federal Common Policy CA G2`. I don't see the TWIC CA in there, so I think we unfortunately will be unable to support it.
